apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Dev overlay: lower resource limits, single replica, no HPA.
patches:
  - target:
      kind: Deployment
      name: postgres
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "250m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"

labels:
  - pairs:
      environment: dev
